"""User-approved demo brands and thematic storefronts; no live affiliations implied."""
from catalog_data import image, product

STORE_CATEGORIES = [
    ('c21', 'Indian Sweets', 'grocery', 'item-sweets'), ('c22', 'Puja & Festive', 'shops', 'item-diya'),
    ('c23', 'Dry Fruits & Nuts', 'grocery', 'item-nuts'), ('c24', 'Breakfast & Cereals', 'grocery', 'item-cereal'),
    ('c25', 'Atta, Rice & Dal', 'grocery', 'item-rice'), ('c26', 'Oils & Ghee', 'grocery', 'item-oil'),
    ('c27', 'Protein & Nutrition', 'grocery', 'item-protein'), ('c28', 'Sports & Fitness', 'shops', 'item-dumbbell'),
    ('c29', 'Tea & Coffee', 'grocery', 'item-coffee-jar'), ('c30', 'Cleaning Essentials', 'grocery', 'item-detergent'),
    ('c31', 'Bath & Body', 'beauty', 'item-bodywash'), ('c32', 'Chocolates & Gifts', 'grocery', 'item-chocolate'),
]
BRAND_ROWS = [
    ('haldirams', "Haldiram’s", 'grocery', 'item-sweets'), ('bikaji', 'Bikaji', 'grocery', 'item-sweets'),
    ('chitale', 'Chitale Bandhu', 'grocery', 'item-sweets'), ('mangaldeep', 'Mangaldeep', 'shops', 'item-diya'),
    ('latur-artisans', 'Latur Artisans', 'shops', 'item-dandiya'), ('farmley', 'Farmley', 'grocery', 'item-nuts'),
    ('happilo', 'Happilo', 'grocery', 'item-nuts'), ('quaker', 'Quaker', 'grocery', 'item-cereal'),
    ('kelloggs', 'Kellogg’s', 'grocery', 'item-cereal'), ('saffola', 'Saffola', 'grocery', 'item-oil'),
    ('aashirvaad', 'Aashirvaad', 'grocery', 'item-rice'), ('india-gate', 'India Gate', 'grocery', 'item-rice'),
    ('fortune', 'Fortune', 'grocery', 'item-oil'), ('muscleblaze', 'MuscleBlaze', 'grocery', 'item-protein'),
    ('yogabar', 'Yoga Bar', 'grocery', 'item-protein'), ('boldfit', 'Boldfit', 'shops', 'item-yoga'),
    ('nivia', 'Nivia', 'shops', 'item-dumbbell'), ('yonex', 'Yonex', 'shops', 'item-badminton'),
    ('nescafe', 'Nescafé', 'grocery', 'item-coffee-jar'), ('tata-tea', 'Tata Tea', 'grocery', 'item-coffee-jar'),
    ('surf-excel', 'Surf Excel', 'grocery', 'item-detergent'), ('lizol', 'Lizol', 'grocery', 'item-detergent'),
    ('dove', 'Dove', 'beauty', 'item-bodywash'), ('plum', 'Plum', 'beauty', 'item-facecream'),
    ('minimalist', 'Minimalist', 'beauty', 'item-facecream'), ('cadbury', 'Cadbury', 'grocery', 'item-chocolate'),
    ('nestle', 'Nestlé', 'grocery', 'item-chocolate'), ('lays', 'Lay’s', 'grocery', 'item-chips'),
    ('bingo', 'Bingo!', 'grocery', 'item-chips'), ('britannia', 'Britannia', 'grocery', 'bread'),
]
STORE_BRANDS = [{'id': bid, 'name': name, 'department': dept, 'logo': '', 'image': image(asset), 'tagline': 'Discover the collection · demo brand listing'} for bid, name, dept, asset in BRAND_ROWS]
ROWS = [
    ('sf1', 'Haldiram’s Modak Selection', '200 g', 149, 180, 'item-sweets', 'haldirams', 'c21'),
    ('sf2', 'Bikaji Besan Laddoo', '250 g', 129, 160, 'item-sweets', 'bikaji', 'c21'),
    ('sf3', 'Chitale Kesar Modak', '12 pieces', 249, 299, 'item-sweets', 'chitale', 'c21'),
    ('sf4', 'Brass Diya Set', '2 pieces', 119, 159, 'item-diya', 'mangaldeep', 'c22'),
    ('sf5', 'Marigold Toran', '1 garland', 79, 99, 'item-marigold', 'latur-artisans', 'c22'),
    ('sf6', 'Navratri Dandiya Sticks', '1 pair', 99, 149, 'item-dandiya', 'latur-artisans', 'c22'),
    ('sf7', 'Festive Diya Gift Box', '4 pieces', 199, 249, 'item-diya', 'mangaldeep', 'c22'),
    ('sf8', 'Chitale Celebration Sweets', '500 g', 349, 420, 'item-sweets', 'chitale', 'c21'),
    ('sn1', 'Farmley Premium Almonds', '200 g', 189, 249, 'item-nuts', 'farmley', 'c23'),
    ('sn2', 'Happilo Mixed Nuts', '200 g', 199, 269, 'item-nuts', 'happilo', 'c23'),
    ('sn3', 'Farmley Roasted Cashews', '100 g', 129, 169, 'item-nuts', 'farmley', 'c23'),
    ('sn4', 'Happilo Festive Nut Mix', '400 g', 399, 499, 'item-nuts', 'happilo', 'c23'),
    ('sg1', 'Quaker Rolled Oats', '400 g', 99, 130, 'item-cereal', 'quaker', 'c24'),
    ('sg2', 'Kellogg’s Corn Flakes', '250 g', 149, 175, 'item-cereal', 'kelloggs', 'c24'),
    ('sg3', 'Saffola Masala Oats', '500 g', 179, 220, 'item-cereal', 'saffola', 'c24'),
    ('sg4', 'Aashirvaad Whole Wheat Atta', '1 kg', 59, 68, 'item-rice', 'aashirvaad', 'c25'),
    ('sg5', 'India Gate Basmati Rice', '1 kg', 129, 169, 'item-rice', 'india-gate', 'c25'),
    ('sg6', 'Fortune Toor Dal', '500 g', 79, 95, 'item-rice', 'fortune', 'c25'),
    ('sg7', 'Fortune Sunflower Oil', '1 litre', 149, 180, 'item-oil', 'fortune', 'c26'),
    ('sg8', 'Saffola Gold Oil', '1 litre', 189, 220, 'item-oil', 'saffola', 'c26'),
    ('sp1', 'MuscleBlaze Whey Protein', '500 g · illustrative pack', 1299, 1599, 'item-protein', 'muscleblaze', 'c27'),
    ('sp2', 'Yoga Bar Protein Mix', '400 g', 349, 449, 'item-protein', 'yogabar', 'c27'),
    ('sp3', 'Yoga Bar Breakfast Muesli', '400 g', 249, 329, 'item-cereal', 'yogabar', 'c24'),
    ('sp4', 'Boldfit Yoga Mat', '1 piece · sage', 499, 699, 'item-yoga', 'boldfit', 'c28'),
    ('sp5', 'Nivia Dumbbell Pair', '2 × 2 kg', 699, 899, 'item-dumbbell', 'nivia', 'c28'),
    ('sp6', 'Yonex Badminton Set', '1 racket + shuttle', 899, 1199, 'item-badminton', 'yonex', 'c28'),
    ('sp7', 'Boldfit Training Dumbbells', '2 × 1 kg', 399, 549, 'item-dumbbell', 'boldfit', 'c28'),
    ('sp8', 'Nivia Exercise Mat', '1 piece', 449, 599, 'item-yoga', 'nivia', 'c28'),
    ('sc1', 'Nescafé Classic Coffee', '50 g', 179, 210, 'item-coffee-jar', 'nescafe', 'c29'),
    ('sc2', 'Tata Tea Premium', '250 g', 119, 145, 'item-coffee-jar', 'tata-tea', 'c29'),
    ('sc3', 'Nescafé Gold Coffee', '100 g', 449, 549, 'item-coffee-jar', 'nescafe', 'c29'),
    ('se1', 'Surf Excel Liquid Detergent', '1 litre', 199, 250, 'item-detergent', 'surf-excel', 'c30'),
    ('se2', 'Lizol Floor Cleaner', '500 ml', 99, 125, 'item-detergent', 'lizol', 'c30'),
    ('se3', 'Dove Nourishing Body Wash', '250 ml', 179, 225, 'item-bodywash', 'dove', 'c31'),
    ('se4', 'Plum Body Wash', '240 ml', 249, 299, 'item-bodywash', 'plum', 'c31'),
    ('se5', 'Minimalist Daily Moisturiser', '50 g', 299, 349, 'item-facecream', 'minimalist', 'c15'),
    ('se6', 'Plum Green Tea Cream', '50 ml', 349, 449, 'item-facecream', 'plum', 'c15'),
    ('se7', 'Lizol Home Care Starter Pack', '2 × 500 ml', 179, 230, 'item-detergent', 'lizol', 'c8'),
    ('st1', 'Cadbury Dairy Milk', '55 g', 49, 60, 'item-chocolate', 'cadbury', 'c32'),
    ('st2', 'Nestlé Dark Chocolate', '90 g', 99, 125, 'item-chocolate', 'nestle', 'c32'),
    ('st3', 'Cadbury Celebration Box', '150 g', 199, 250, 'item-chocolate', 'cadbury', 'c32'),
    ('st4', 'Lay’s Classic Salted', '90 g', 35, 40, 'item-chips', 'lays', 'c3'),
    ('st5', 'Bingo! Masala Crunch', '100 g', 30, 35, 'item-chips', 'bingo', 'c3'),
    ('st6', 'Haldiram’s Namkeen', '200 g', 59, 75, 'item-chips', 'haldirams', 'c3'),
    ('st7', 'Britannia Milk Bread', '400 g', 45, 50, 'bread', 'britannia', 'c5'),
    ('st8', 'Britannia Breakfast Toast', '200 g', 39, 50, 'bread', 'britannia', 'c5'),
]
DEPARTMENTS = {b['id']: b['department'] for b in STORE_BRANDS}
STORE_PRODUCTS = [product(pid, name, size, price, mrp, asset, DEPARTMENTS[brand], brand, cat) for pid, name, size, price, mrp, asset, brand, cat in ROWS]
THEMED_STORES = [
    {'id': 'festive', 'name': 'Festive Time', 'subtitle': 'Little rituals. Big celebrations.', 'eyebrow': 'THE FESTIVE EDIT', 'categories': ['c21', 'c22', 'c23', 'c32'], 'icon': 'sparkles-outline', 'image': image('store-festive'), 'sections': ['Treats for Bappa, with love', 'A little sparkle for Navratri']},
    {'id': 'fitness', 'name': 'Sports & Fitness', 'subtitle': 'Show up. Get stronger. Repeat.', 'eyebrow': 'FIND YOUR STRONG', 'categories': ['c28', 'c27', 'c24', 'c23'], 'icon': 'barbell-outline', 'image': image('store-fitness'), 'sections': ['Your next personal best', 'Fuel the everyday athlete']},
    {'id': 'trending', 'name': 'Trending Now', 'subtitle': 'Good finds. Main-character energy.', 'eyebrow': 'THE CITY IS TALKING', 'categories': ['c19', 'c18', 'c15', 'c31', 'c32'], 'icon': 'trending-up-outline', 'image': image('store-trending'), 'sections': ['The most-wanted edit', 'Small upgrades. Big mood.']},
    {'id': 'gourmet', 'name': 'Gourmet Treats', 'subtitle': 'A little indulgence, just for you.', 'eyebrow': 'SAVOUR THE LITTLE THINGS', 'categories': ['c29', 'c32', 'c3', 'c5', 'c21'], 'icon': 'cafe-outline', 'image': image('store-gourmet'), 'sections': ['Made for your coffee break', 'Something sweet. Something crunchy.']},
    {'id': 'everyday', 'name': 'Everyday Essentials', 'subtitle': 'Your daily list. Beautifully sorted.', 'eyebrow': 'LITTLE THINGS, TAKEN CARE OF', 'categories': ['c1', 'c2', 'c25', 'c26', 'c30', 'c31'], 'icon': 'leaf-outline', 'image': image('store-everyday'), 'sections': ['Fresh starts here', 'Restock your happy place']},
]