import { View, Text, Pressable, StyleSheet, Linking, ScrollView } from 'react-native';
import Icon from '@react-native-vector-icons/ionicons';
import { ChatMessage } from '../assistant';
import { useCatalog } from '../use-catalog';
import { colors } from '../theme';
import { ProductCard } from './product-card';
import { AssistantBasket } from './assistant-basket';

export function AssistantMessage({ message, index, onError }: { message: ChatMessage; index: number; onError: (s: string) => void }) {
  const { data } = useCatalog(); const user = message.role === 'user';
  const products = (message.product_ids || []).flatMap(id => data?.products.filter(p => p.id === id) || []);
  return <View testID={`assistant-message-${index}`} style={styles.wrap}><View style={[styles.bubble, user && styles.user]}>{!user && <Text style={styles.label}>ONE AI</Text>}<Text testID={`assistant-message-text-${index}`} selectable style={[styles.text, user && styles.userText]}>{message.text}</Text></View>{products.length > 0 && <><Text testID={`assistant-product-label-${index}`} style={styles.caption}>FROM OUR SAMPLE CATALOGUE</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.products}>{products.map(p => <ProductCard key={p.id} product={p} scope={`ai-${index}`} width={140} />)}</ScrollView><AssistantBasket products={products} budget={message.budget} index={index} /></>}{!!message.search_links?.length && <View style={styles.compare}><Text testID={`assistant-comparison-notice-${index}`} style={styles.compareTitle}>Check prices elsewhere</Text>{!!message.comparison_query && <Text testID={`assistant-comparison-product-${index}`} style={styles.linkText}>{message.comparison_query}</Text>}<Text style={styles.note}>External searches, not live quotes. Check pack size, delivery fees and availability.</Text>{message.search_links.map((link, i) => <Pressable key={link.merchant} testID={`assistant-compare-${index}-${i}`} accessibilityLabel={`Search ${link.merchant}`} onPress={() => Linking.openURL(link.url).catch(() => onError('Could not open this retailer. Please try again.'))} style={styles.link}><Text style={styles.linkText}>{link.merchant}</Text><Icon name="open-outline" size={15} color={colors.forest} /></Pressable>)}</View>}</View>;
}
const styles = StyleSheet.create({ wrap: { marginBottom: 22 }, bubble: { marginHorizontal: 18, padding: 17, backgroundColor: colors.cream, borderRadius: 24, borderTopLeftRadius: 6 }, user: { alignSelf: 'flex-end', maxWidth: '88%', backgroundColor: colors.forestDeep, borderTopLeftRadius: 24, borderBottomRightRadius: 6 }, label: { color: colors.forest, fontSize: 8, fontWeight: '800', letterSpacing: 1.5, marginBottom: 9 }, text: { color: colors.onSurface, fontSize: 13, lineHeight: 21 }, userText: { color: colors.surface }, caption: { color: colors.muted, fontSize: 8, letterSpacing: 1, marginLeft: 22, marginTop: 19, marginBottom: 10 }, products: { paddingHorizontal: 18, gap: 10 }, compare: { margin: 18, marginBottom: 0, padding: 16, backgroundColor: colors.limeSoft, borderRadius: 22 }, compareTitle: { color: colors.forest, fontSize: 12, fontWeight: '700' }, note: { color: colors.muted, fontSize: 10, lineHeight: 16, marginTop: 5, marginBottom: 6 }, link: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.cityMid }, linkText: { color: colors.forest, fontSize: 11, fontWeight: '600' } });