import { View, Text, Pressable, StyleSheet } from 'react-native';
import Icon from '@react-native-vector-icons/ionicons';
import { Product } from '../api';
import { colors } from '../theme';
import { useCart } from '../cart';
export function AssistantBasket({ products, budget, index }: { products: Product[]; budget?: number | null; index: number }) {
  const { add, qtyOf } = useCart(); const missing = products.filter(p => !qtyOf(p.id));
  const total = products.reduce((n, p) => n + p.price, 0);
  return <View testID={`assistant-basket-${index}`} style={styles.box}><View style={styles.row}><View style={styles.copy}><Text style={styles.label}>YOUR SUGGESTED BASKET</Text><Text testID={`assistant-basket-total-${index}`} style={styles.total}>₹{total}<Text style={styles.meta}> · one of each</Text></Text></View>{!!budget && <Text testID={`assistant-budget-remaining-${index}`} style={styles.remaining}>₹{Math.max(0, budget-total)} within budget</Text>}</View><Text style={styles.note}>Sample prices. Delivery fees calculated in cart. Items already in your bag won’t be added twice.</Text><Pressable testID={`assistant-add-basket-${index}`} disabled={!missing.length} onPress={() => missing.forEach(p => add(p))} style={[styles.button, !missing.length && styles.disabled]}><Icon name={missing.length ? 'bag-add-outline' : 'checkmark-circle-outline'} size={18} color={colors.forest} /><Text style={styles.buttonText}>{missing.length ? `Add ${missing.length} missing item${missing.length === 1 ? '' : 's'} · ₹${missing.reduce((n,p) => n+p.price,0)}` : 'All picks are in your bag'}</Text></Pressable></View>;
}
const styles = StyleSheet.create({ box: { marginHorizontal: 18, marginTop: 12, padding: 16, borderRadius: 22, backgroundColor: colors.limeSoft }, row: { flexDirection: 'row', alignItems: 'center', gap: 8 }, copy: { flex: 1 }, label: { fontSize: 8, letterSpacing: 1, color: colors.forest, fontWeight: '700' }, total: { color: colors.forest, fontSize: 22, fontWeight: '700', marginTop: 7 }, meta: { fontSize: 10, fontWeight: '400' }, remaining: { fontSize: 10, maxWidth: 80, lineHeight: 15, color: colors.forest, textAlign: 'right' }, note: { fontSize: 9, lineHeight: 15, color: colors.muted, marginTop: 8 }, button: { minHeight: 46, marginTop: 12, backgroundColor: colors.surface, borderRadius: 23, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, buttonText: { fontSize: 11, fontWeight: '700', color: colors.forest }, disabled: { opacity: 0.6 } });