import { useEffect, useRef, useState } from 'react';
import { View, Text, Pressable, Animated, StyleSheet, AccessibilityInfo, Platform } from 'react-native';
import { Image } from 'expo-image';
import { LinearGradient } from 'expo-linear-gradient';
import { paletteFor } from '../departments';
import { usePathname, useRouter } from 'expo-router';
import Icon from '@react-native-vector-icons/ionicons';
import { colors } from '../theme';
import { mediaUrl } from '../api';

const stories = {
  home: { eyebrow: 'THE LITTLE JOYS OF EVERYDAY', title: 'Everyday, a little\nmore delicious.', copy: 'A slice of goodness. A whole lot of happy.', asset: 'amul-cutout', tag: 'Amul goodness', detail: 'Cheese favourites · from ₹145', cta: 'Shop Amul', route: '/brand/amul', color: colors.forest, badge: 'made for\nhappy bites', icon: 'heart-outline' },
  grocery: { eyebrow: 'FRESH FINDS, FAMILIAR FAVOURITES', title: 'Little slices.\nBig happiness.', copy: 'Your daily basket deserves a little Amul.', asset: 'amul-cutout', tag: 'The dairy edit', detail: 'Milk, butter, cheese & more', cta: 'Explore Amul', route: '/brand/amul', color: colors.forest, badge: 'daily\ngoodness', icon: 'leaf-outline' },
  food: { eyebrow: 'FRESH CRAVINGS, GOLDEN MOMENTS', title: 'A good mood,\nwith a side of fries.', copy: 'Your favourite bites are just around the corner.', asset: 'burger', tag: 'McDonald’s', detail: 'Your next craving · from ₹129', cta: 'Find my bite', route: '/brand/mcdonalds', color: colors.food, badge: 'a little\ncrave-worthy', icon: 'flame-outline' },
  shops: { eyebrow: 'NEW FINDS. YOUR KIND OF STYLE.', title: 'A little fresh air\nfor your wardrobe.', copy: 'Find something that feels a little more you.', asset: 'sneakers', tag: 'The style edit', detail: 'Nike favourites · from ₹899', cta: 'Find my style', route: '/brand/nike', color: colors.book, badge: 'step into\nsomething new', icon: 'sparkles-outline' },
  care: { eyebrow: 'SLOW DOWN. GLOW A LITTLE.', title: 'Your everyday\ncare, elevated.', copy: 'Beauty favourites & feel-good essentials.', asset: 'skincare', tag: 'The NIVEA edit', detail: 'Soft care · from ₹189', cta: 'Find my glow', route: '/brand/nivea', color: colors.beauty, badge: 'a little\nself-love', icon: 'flower-outline' },
  'book-it': { eyebrow: 'YOUR CITY. A LITTLE MORE ALIVE.', title: 'Good times,\noutside your feed.', copy: 'Big screens, live scenes & new memories.', asset: 'concert', tag: 'Latur After Hours', detail: 'Live music · sample experience', cta: 'Make a plan', route: '/booking/e3', color: colors.book, badge: 'make room\nfor memories', icon: 'musical-notes-outline' },
};
export type SpotlightVariant = keyof typeof stories;
export function BrandSpotlight({ variant = 'home', switchable = false }: { variant?: SpotlightVariant; switchable?: boolean }) {
  const [selected, setSelected] = useState<SpotlightVariant>(variant);
  const story = stories[switchable ? selected : variant];
  const float = useRef(new Animated.Value(0)).current; const router = useRouter(); const palette = paletteFor(usePathname());
  useEffect(() => { let animation: Animated.CompositeAnimation | undefined; let disposed = false; AccessibilityInfo.isReduceMotionEnabled().then(reduce => { if (!reduce && !disposed) { animation = Animated.loop(Animated.sequence([Animated.timing(float, { toValue: -7, duration: 2100, useNativeDriver: Platform.OS !== 'web' }), Animated.timing(float, { toValue: 0, duration: 2100, useNativeDriver: Platform.OS !== 'web' })])); animation.start(); } }); return () => { disposed = true; animation?.stop(); }; }, [float]);
  return <LinearGradient testID={`spotlight-${variant}`} colors={[palette.mid, palette.fade, colors.surface]} locations={[0, 0.83, 1]} style={styles.wrap}>
    <View style={styles.hero}><View style={styles.glow} /><View style={styles.orbit} />
      <View style={styles.copy}><Text style={[styles.eyebrow, { color: story.color }]}>{story.eyebrow}</Text><Text testID={`spotlight-title-${variant}`} style={styles.title}>{story.title}</Text><Text style={styles.description}>{story.copy}</Text><Pressable testID={`spotlight-shop-${variant}`} accessibilityLabel={story.cta} onPress={() => router.push(story.route as any)} style={({ pressed }) => [styles.cta, { backgroundColor: story.color }, pressed && styles.pressed]}><Text style={styles.ctaText}>{story.cta}</Text><Icon name="arrow-forward" size={14} color={colors.surface} /></Pressable></View>
      <Animated.View style={[styles.art, { transform: [{ translateY: float }, { rotate: '-8deg' }] }]}><Image testID={`spotlight-image-${variant}`} source={mediaUrl(story.asset === 'amul-cutout' ? 'amul-float' : story.asset)} style={styles.image} contentFit={story.asset === 'amul-cutout' ? 'contain' : 'cover'} /></Animated.View>
      <View style={styles.sticker}><Icon name={story.icon as any} size={16} color={story.color} /><Text style={[styles.stickerText, { color: story.color }]}>{story.badge}</Text></View>
      <Pressable testID={`spotlight-brand-${variant}`} accessibilityLabel={`Explore ${story.tag}`} onPress={() => router.push(story.route as any)} style={styles.floatingLabel}><View style={[styles.dot, { backgroundColor: story.color }]} /><View><Text style={styles.brandTag}>{story.tag}</Text><Text style={styles.detail}>{story.detail}</Text></View><Icon name="arrow-up-right-box-outline" size={14} color={story.color} /></Pressable>
    </View>
    {switchable ? <View style={styles.storyTabs}>{[{ id: 'home', text: 'Daily goodness' }, { id: 'shops', text: 'Fresh style' }, { id: 'care', text: 'A little self-care' }].map(s => <Pressable testID={`spotlight-switch-${s.id}`} key={s.id} onPress={() => setSelected(s.id as SpotlightVariant)} style={[styles.storyTab, selected === s.id && styles.storySelected]}><View style={[styles.tinyDot, selected === s.id && { backgroundColor: colors.forest }]} /><Text style={styles.storyText}>{s.text}</Text></Pressable>)}</View> : <Text testID={`spotlight-notice-${variant}`} style={styles.sample}>A sample brand spotlight · curated for you</Text>}
  </LinearGradient>;
}
const styles = StyleSheet.create({
  wrap: { paddingBottom: 13 }, hero: { height: 253, position: 'relative', overflow: 'hidden' }, copy: { position: 'absolute', top: 17, left: 22, width: '58%', zIndex: 2 }, eyebrow: { fontSize: 6.5, fontWeight: '600', letterSpacing: 1.2 }, title: { fontSize: 25, lineHeight: 30, fontWeight: '600', letterSpacing: -0.8, color: colors.onSurface, marginTop: 13 }, description: { color: colors.inkSoft, fontSize: 10, lineHeight: 16, marginTop: 10, width: 154 }, cta: { height: 44, paddingHorizontal: 15, borderRadius: 24, flexDirection: 'row', alignItems: 'center', gap: 11, alignSelf: 'flex-start', marginTop: 17 }, ctaText: { color: colors.surface, fontSize: 10, fontWeight: '600' },
  art: { position: 'absolute', width: '47%', height: 182, right: -9, top: 32 }, image: { width: '100%', height: '100%', borderTopLeftRadius: 65, borderBottomRightRadius: 65, borderTopRightRadius: 32, borderBottomLeftRadius: 32 }, glow: { position: 'absolute', width: 222, height: 208, borderRadius: 108, backgroundColor: colors.glass, right: -36, top: 20, transform: [{ rotate: '-25deg' }] }, orbit: { position: 'absolute', width: 205, height: 200, borderRadius: 100, borderWidth: 1, borderColor: colors.glassLine, top: 40, right: -10 }, sticker: { position: 'absolute', right: 17, top: 5, backgroundColor: colors.glassBright, width: 65, height: 65, borderRadius: 33, alignItems: 'center', justifyContent: 'center', gap: 3, transform: [{ rotate: '11deg' }], zIndex: 3 }, stickerText: { textAlign: 'center', fontSize: 7, lineHeight: 10, fontWeight: '500' }, floatingLabel: { position: 'absolute', bottom: 0, right: 18, flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 12, minHeight: 44, borderRadius: 22, backgroundColor: colors.glassBright, borderWidth: 1, borderColor: colors.glassLine, transform: [{ rotate: '-3deg' }], boxShadow: [{ offsetX: 0, offsetY: 5, blurRadius: 18, color: colors.shadow }] }, dot: { width: 6, height: 6, borderRadius: 3 }, brandTag: { fontSize: 9, color: colors.onSurface, fontWeight: '600' }, detail: { fontSize: 7, color: colors.muted, marginTop: 3 }, storyTabs: { flexDirection: 'row', marginHorizontal: 20, marginTop: 15, gap: 5 }, storyTab: { flex: 1, minHeight: 44, borderRadius: 24, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 5 }, storySelected: { backgroundColor: colors.glassBright }, tinyDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: colors.borderStrong }, storyText: { fontSize: 8, color: colors.onSurface }, sample: { marginTop: 16, textAlign: 'center', fontSize: 8, color: colors.muted }, pressed: { opacity: 0.7 },
});