import { useState } from 'react';
import { View, Text, Modal, Pressable, ScrollView, StyleSheet } from 'react-native';
import Icon from '@react-native-vector-icons/ionicons';
import { useCustomer, PaymentMethod } from '../customer';
import { colors } from '../theme';
import { PaymentOptions, paymentLabel } from './payment-options';
export function CheckoutPayment() {
  const { payment, update, ready } = useCustomer(); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const select = async (method: PaymentMethod) => { setBusy(true); setError(''); try { await update({ payment: method }); setOpen(false); } catch { setError('Could not save your selection. Please try again.'); } finally { setBusy(false); } };
  return <><Pressable testID="checkout-payment-open" disabled={!ready} accessibilityLabel="Choose payment method" onPress={() => setOpen(true)} style={s.row}><View style={s.icon}><Icon name="card-outline" size={23} color={colors.shops} /></View><View style={s.copy}><Text style={s.label}>Payment method</Text><Text testID="checkout-selected-payment" style={s.value}>{paymentLabel(payment)}</Text><Text style={s.note}>Sample order · you won’t be charged</Text></View><Text style={s.change}>Change</Text></Pressable><Modal transparent visible={open} animationType="slide" onRequestClose={() => setOpen(false)}><View style={s.overlay}><View testID="checkout-payment-sheet" style={s.sheet}><View style={s.header}><Text style={s.title}>Your way to pay</Text><Pressable testID="checkout-payment-close" accessibilityLabel="Close payment options" onPress={() => setOpen(false)} style={s.close}><Icon name="close" size={22} color={colors.onSurface} /></Pressable></View><ScrollView contentContainerStyle={s.scroll}><Text testID="checkout-payment-selection-notice" style={s.explain}>Choose a method for this sample order. No payment is processed and no financial details are collected.</Text><PaymentOptions scope="checkout" value={payment} onChange={select} disabled={busy} />{busy && <Text testID="checkout-payment-saving" style={s.explain}>Saving your choice…</Text>}{!!error && <Text testID="checkout-payment-error" style={s.error}>{error}</Text>}</ScrollView></View></View></Modal></>;
}
const s = StyleSheet.create({ row: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: colors.surface, padding: 17, borderRadius: 23, marginTop: 12 }, icon: { width: 38, height: 44, justifyContent: 'center' }, copy: { flex: 1 }, label: { fontSize: 11, color: colors.muted }, value: { fontSize: 14, fontWeight: '700', color: colors.onSurface, marginTop: 4 }, note: { fontSize: 9, color: colors.muted, marginTop: 5 }, change: { fontSize: 12, color: colors.shops, fontWeight: '700' }, overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: colors.overlay }, sheet: { backgroundColor: colors.surface, borderTopLeftRadius: 30, borderTopRightRadius: 30, padding: 22, paddingBottom: 30, maxHeight: '85%' }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, close: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, title: { color: colors.onSurface, fontSize: 22, fontWeight: '700' }, explain: { color: colors.muted, fontSize: 12, lineHeight: 20, marginBottom: 20 }, error: { color: colors.onError, padding: 10 }, scroll: { paddingBottom: 20 } });