import { useCallback, useEffect, useRef, useState } from 'react';
import { View, Text, TextInput, Pressable, Animated, StyleSheet } from 'react-native';
import { Image } from 'expo-image';
import { LinearGradient } from 'expo-linear-gradient';
import { useRouter, useFocusEffect } from 'expo-router';
import Icon from '@react-native-vector-icons/ionicons';
import { ThemedStore, mediaUrl } from '../api';
import { colors } from '../theme';
import { nativeDriver, useMotionAllowed } from '../motion';
import { storePalette } from '../store-palettes';
import { StoreAtmosphere } from './store-atmosphere';
const artFor = (id: string, festival: string) => id === 'festive' ? (festival === 'ganesh' ? ['festival-bappa', 'float-item-sweets', 'float-item-diya'] : ['festival-navratri', 'float-item-dandiya', 'float-item-marigold']) : id === 'fitness' ? ['float-item-dumbbell', 'float-item-protein', 'float-item-yoga'] : id === 'trending' ? ['float-headphones-v2', 'float-sneaker-v2', 'float-item-chocolate'] : id === 'gourmet' ? ['float-item-coffee-jar', 'float-item-chocolate', 'float-item-nuts'] : ['float-amul-milk', 'float-item-rice', 'float-item-detergent'];
type Props = { store: ThemedStore; query: string; setQuery: (q: string) => void; budget: boolean; setBudget: (b: boolean) => void; festival: string; setFestival: (f: string) => void };
export function CollectionScene({ store, query, setQuery, budget, setBudget, festival, setFestival }: Props) {
  const id = store.id; const palette = storePalette(id, festival); const router = useRouter(); const motion = useMotionAllowed(); const progress = useRef(new Animated.Value(0)).current; const enter = useRef(new Animated.Value(1)).current; const [focused, setFocused] = useState(true);
  useFocusEffect(useCallback(() => { setFocused(true); return () => setFocused(false); }, []));
  useEffect(() => { if (!motion || !focused) { progress.setValue(0.5); enter.setValue(1); return; } enter.setValue(0); const intro = Animated.spring(enter, { toValue: 1, friction: 9, useNativeDriver: nativeDriver }); const loop = Animated.loop(Animated.sequence([Animated.timing(progress, { toValue: 1, duration: id === 'fitness' ? 1500 : 2300, useNativeDriver: nativeDriver }), Animated.timing(progress, { toValue: 0, duration: id === 'fitness' ? 1500 : 2300, useNativeDriver: nativeDriver })])); intro.start(); loop.start(); return () => { loop.stop(); intro.stop(); }; }, [id, festival, motion, focused, progress, enter]);
  const title = id === 'festive' ? festival === 'ganesh' ? 'Bappa’s here.\nSo is the joy.' : 'Nine nights.\nEndless colour.' : id === 'fitness' ? 'Find your\neveryday strong.' : id === 'trending' ? 'Good finds.\nGreat mood.' : id === 'gourmet' ? 'A little sip.\nA lot of bliss.' : 'Little things.\nLife, sorted.';
  const assets = artFor(id, festival);
  return <LinearGradient testID={`collection-animated-scene-${id}`} colors={[palette.top, palette.soft]} style={s.scene}>
    <StoreAtmosphere id={id} festival={festival} active={focused} />
    <View style={s.header}><Pressable testID="collection-back" accessibilityLabel="Go back" style={s.round} onPress={() => router.canGoBack() ? router.back() : router.replace('/categories')}><Icon name="arrow-back" size={21} color={palette.ink} /></Pressable><View style={s.headerCopy}><Text testID="collection-title" style={[s.headerTitle, { color: palette.ink }]}>{store.name}</Text><Text testID="collection-store-caption" style={s.caption}>A ONECITY LITTLE WORLD</Text></View><Pressable testID="collection-ai" accessibilityLabel="Ask One about this store" onPress={() => router.push(`/assistant?prompt=${encodeURIComponent(`Help me shop the ${store.name} collection within ₹500.`)}` as any)} style={s.round}><Icon name="sparkles-outline" size={20} color={palette.ink} /></Pressable></View>
    <View style={s.search}><Icon name="search-outline" size={18} color={palette.ink} /><TextInput testID="collection-search" accessibilityLabel="Search this store" value={query} onChangeText={setQuery} placeholder={`Search ${store.name.toLowerCase()}`} placeholderTextColor={colors.muted} style={s.input} /><Pressable testID="collection-budget-filter" accessibilityState={{ selected: budget }} onPress={() => setBudget(!budget)} style={[s.budget, budget && { backgroundColor: palette.top }]}><Text style={[s.budgetText, { color: palette.ink }]}>Under ₹199</Text></Pressable></View>
    <View style={s.stage}><View style={s.copy}><Text testID="collection-eyebrow" style={[s.eyebrow, { color: palette.ink }]}>{store.eyebrow}</Text><Text testID="collection-hero-title" style={[s.title, { color: palette.ink }]}>{title}</Text><Text testID="collection-subtitle" style={s.subtitle}>{id === 'festive' ? festival === 'ganesh' ? 'Modaks, little rituals & a whole lot of love.' : 'Twirl into the joy of garba nights.' : store.subtitle}</Text><View style={s.season}><Icon name={id === 'festive' ? 'flower-outline' : store.icon as any} size={13} color={palette.ink} /><Text style={[s.seasonText, { color: palette.ink }]}>{id === 'festive' ? festival === 'ganesh' ? 'GANPATI BAPPA MORYA' : 'LET’S CELEBRATE' : 'CURATED WITH LOVE'}</Text></View></View>
      <Animated.View testID={`collection-main-motion-${id}`} style={[s.mainArt, { opacity: enter, transform: [{ translateY: progress.interpolate({ inputRange: [0, 1], outputRange: [5, -9] }) }, { scale: enter.interpolate({ inputRange: [0, 1], outputRange: [0.82, 1] }) }, { rotate: progress.interpolate({ inputRange: [0, 1], outputRange: id === 'festive' && festival === 'ganesh' ? ['-1deg', '1deg'] : ['-7deg', '6deg'] }) }] }]}><Image testID={`collection-hero-image-${id}`} accessibilityLabel={id === 'festive' ? festival === 'ganesh' ? 'Lord Ganesha with modak sweets' : 'Navratri garba dancer' : store.name} source={mediaUrl(assets[0])} contentFit="contain" style={s.image} /></Animated.View>
      {assets.slice(1).map((asset, i) => <Animated.View testID={`collection-product-motion-${i}`} key={asset} style={[s.miniArt, i ? s.miniRight : s.miniLeft, { opacity: enter, transform: [{ translateY: progress.interpolate({ inputRange: [0, 1], outputRange: i ? [-8, 8] : [8, -8] }) }, { rotate: progress.interpolate({ inputRange: [0, 1], outputRange: i ? ['8deg', '-10deg'] : ['-12deg', '8deg'] }) }] }]}><Image testID={`collection-floating-product-${i}`} source={mediaUrl(asset)} contentFit="contain" style={s.image} /></Animated.View>)}
    </View>
    {id === 'festive' ? <View testID="festival-selection" style={s.festivals}>{[{ id: 'ganesh', label: 'Ganesh Chaturthi', icon: 'flower-outline' }, { id: 'navratri', label: 'Navratri nights', icon: 'sparkles-outline' }].map(f => <Pressable testID={`festival-${f.id}`} accessibilityState={{ selected: festival === f.id }} key={f.id} onPress={() => setFestival(f.id)} style={[s.festival, { borderColor: festival === f.id ? palette.ink : colors.transparent, backgroundColor: festival === f.id ? colors.surface : colors.glass }]}><Icon name={f.icon as any} size={15} color={palette.ink} /><Text style={[s.festivalLabel, { color: palette.ink }]}>{f.label}</Text></Pressable>)}</View> : <Text testID="collection-scene-footer" style={[s.sceneFoot, { color: palette.ink }]}>A FEW LITTLE FINDS. A WHOLE NEW MOOD.</Text>}
  </LinearGradient>;
}
const s = StyleSheet.create({ scene: { overflow: 'hidden', borderBottomLeftRadius: 32, borderBottomRightRadius: 32, paddingBottom: 20 }, header: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 14, paddingTop: 10, paddingBottom: 10 }, round: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 22, backgroundColor: colors.glass }, headerCopy: { flex: 1 }, headerTitle: { fontSize: 19, fontWeight: '800' }, caption: { fontSize: 7, color: colors.muted, letterSpacing: 1.5, marginTop: 4 }, search: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: colors.glassBright, borderWidth: 1, borderColor: colors.glassLine, borderRadius: 25, marginHorizontal: 18, paddingLeft: 15, paddingRight: 4 }, input: { flex: 1, height: 47, fontSize: 11, color: colors.onSurface }, budget: { minHeight: 44, borderRadius: 23, paddingHorizontal: 10, justifyContent: 'center' }, budgetText: { fontSize: 9, fontWeight: '700' }, stage: { height: 278 }, copy: { position: 'absolute', top: 44, left: 23, width: '47%', zIndex: 2 }, eyebrow: { fontSize: 7, fontWeight: '700', letterSpacing: 1.2 }, title: { fontSize: 28, lineHeight: 33, fontWeight: '800', letterSpacing: -0.9, marginTop: 13 }, subtitle: { fontSize: 11, color: colors.onSurface, lineHeight: 18, marginTop: 12, paddingRight: 5 }, season: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 23 }, seasonText: { fontSize: 6.5, letterSpacing: 0.65, fontWeight: '800' }, mainArt: { position: 'absolute', right: -3, top: 25, width: '53%', height: 208 }, image: { width: '100%', height: '100%' }, miniArt: { position: 'absolute', width: 62, height: 62 }, miniLeft: { left: '49%', bottom: 6 }, miniRight: { right: 8, bottom: 5 }, festivals: { flexDirection: 'row', paddingHorizontal: 18, gap: 8, marginTop: 7 }, festival: { flex: 1, minHeight: 46, borderRadius: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, borderWidth: 1 }, festivalLabel: { fontSize: 11, fontWeight: '600' }, sceneFoot: { marginHorizontal: 23, marginTop: 4, textAlign: 'center', fontSize: 8, fontWeight: '700', letterSpacing: 1.4 } });