import { useEffect, useRef, useState } from 'react';
import { Animated, View, Text, Pressable, StyleSheet } from 'react-native';
import { Image } from 'expo-image';
import { LinearGradient } from 'expo-linear-gradient';
import { useRouter } from 'expo-router';
import Icon from '@react-native-vector-icons/ionicons';
import { useCatalog } from '../use-catalog';
import { colors } from '../theme';
import { mediaUrl } from '../api';
import { nativeDriver, useMotionAllowed } from '../motion';
const stories = [
  { id: 'mcdonalds', title: 'A good mood,\nwith a side of fries.', copy: 'Golden little moments. Made for your cravings.', asset: 'burger', cta: 'Find my bite' },
  { id: 'kfc', title: 'Crispy outside.\nHappy inside.', copy: 'Bring your favourite people. We’ll bring the crunch.', asset: 'chicken', cta: 'Bring the crunch' },
  { id: 'starbucks', title: 'A little pause.\nA lovely latte.', copy: 'Make a little time for your daily coffee ritual.', asset: 'coffee', cta: 'Find my coffee' },
  { id: 'burgerking', title: 'Big flavour.\nYour kind of bite.', copy: 'Burgers, fries and all the good stuff.', asset: 'burger', cta: 'Explore the menu' },
  { id: 'dominos', title: 'Good times,\none slice at a time.', copy: 'Make tonight a pizza kind of night.', asset: 'pizza', cta: 'Pick my pizza' },
];
export function FoodSpotlight() {
  const [selected, setSelected] = useState(0); const { data } = useCatalog(); const story = stories[selected]; const router = useRouter(); const motion = useMotionAllowed(); const float = useRef(new Animated.Value(0)).current; const entrance = useRef(new Animated.Value(1)).current;
  useEffect(() => { if (!motion) { float.setValue(0); entrance.setValue(1); return; } entrance.setValue(0); const intro = Animated.spring(entrance, { toValue: 1, friction: 8, useNativeDriver: nativeDriver }); const loop = Animated.loop(Animated.sequence([Animated.timing(float, { toValue: 1, duration: 1900, useNativeDriver: nativeDriver }), Animated.timing(float, { toValue: 0, duration: 1900, useNativeDriver: nativeDriver })])); intro.start(); loop.start(); return () => { intro.stop(); loop.stop(); }; }, [selected, motion, float, entrance]);
  return <LinearGradient testID="spotlight-food" colors={[colors.foodMid, colors.foodFade, colors.surface]} style={s.wrap}><View style={s.hero}><View style={s.orbit} /><View style={s.copy}><Text testID="food-spotlight-eyebrow" style={s.eyebrow}>FRESH CRAVINGS. FAMILIAR FAVOURITES.</Text><Text testID="spotlight-title-food" style={s.title}>{story.title}</Text><Text testID="food-spotlight-description" style={s.description}>{story.copy}</Text><Pressable testID="spotlight-shop-food" onPress={() => router.push(`/brand/${story.id}` as any)} style={s.cta}><Text style={s.ctaText}>{story.cta}</Text><Icon name="arrow-forward" size={15} color={colors.surface} /></Pressable></View><Animated.View style={[s.art, { opacity: entrance, transform: [{ translateY: float.interpolate({ inputRange: [0, 1], outputRange: [4, -7] }) }, { rotate: float.interpolate({ inputRange: [0, 1], outputRange: ['-7deg', '0deg'] }) }, { scale: entrance.interpolate({ inputRange: [0, 1], outputRange: [0.9, 1] }) }] }]}><Image testID="spotlight-image-food" source={mediaUrl(story.asset)} style={s.image} contentFit="cover" /></Animated.View></View>
    <View testID="food-spotlight-brand-selector" style={s.brands}>{stories.map((item, i) => { const brand = data?.brands.find(b => b.id === item.id); return <Pressable key={item.id} testID={`food-spotlight-select-${item.id}`} accessibilityLabel={`Show ${brand?.name || item.id} spotlight`} accessibilityState={{ selected: selected === i }} onPress={() => setSelected(i)} style={s.brand}><View style={[s.logoWrap, selected === i && s.active]}><Image testID={`food-spotlight-logo-${item.id}`} source={brand?.logo || mediaUrl(item.id)} contentFit="contain" style={s.logo} /></View><Text testID={`food-spotlight-brand-name-${item.id}`} numberOfLines={1} style={s.brandName}>{brand?.name || item.id}</Text></Pressable>; })}</View><Text testID="spotlight-notice-food" style={s.note}>Tap a logo to change the mood · sample brand spotlights</Text>
  </LinearGradient>;
}
const s = StyleSheet.create({ wrap: { paddingBottom: 18 }, hero: { height: 256, overflow: 'hidden' }, orbit: { position: 'absolute', right: -25, top: 32, width: 220, height: 200, borderRadius: 110, backgroundColor: colors.glass }, copy: { position: 'absolute', left: 22, top: 19, width: '58%', zIndex: 2 }, eyebrow: { color: colors.food, fontSize: 6.5, fontWeight: '700', letterSpacing: 0.9 }, title: { fontSize: 26, lineHeight: 32, fontWeight: '700', color: colors.onSurface, marginTop: 14, letterSpacing: -0.7 }, description: { width: '79%', color: colors.food, fontSize: 10, lineHeight: 17, marginTop: 11 }, cta: { minHeight: 44, borderRadius: 23, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: colors.food, alignSelf: 'flex-start', marginTop: 17 }, ctaText: { color: colors.surface, fontSize: 11, fontWeight: '600' }, art: { position: 'absolute', right: -8, top: 49, width: '44%', height: 180 }, image: { width: '100%', height: '100%', borderRadius: 52 }, brands: { flexDirection: 'row', paddingHorizontal: 16, gap: 6, marginTop: 5 }, brand: { flex: 1, alignItems: 'center', gap: 8 }, logoWrap: { width: 53, height: 53, borderRadius: 20, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, active: { borderWidth: 2, borderColor: colors.food, backgroundColor: colors.foodSoft }, logo: { width: 37, height: 37 }, brandName: { fontSize: 8, color: colors.onSurface }, note: { textAlign: 'center', fontSize: 8, color: colors.muted, marginTop: 15 } });