import { useQuery } from '@tanstack/react-query';
import { View, Text, ScrollView, Pressable, StyleSheet, ActivityIndicator } from 'react-native';
import Icon from '@react-native-vector-icons/ionicons';
import { api, Coupon } from '../api';
import { colors } from '../theme';
import { useCart } from '../cart';
import { LoadState } from './catalog-sections';
import { OneGlyph } from './one-button';

export function OneSaver({ onApply, applying }: { onApply: (code: string) => void; applying: boolean }) {
  const { totalPrice, totalMrp, totalItems } = useCart();
  const { data, isError, refetch } = useQuery({ queryKey: ['coupons'], queryFn: () => api<Coupon[]>('/coupons') });
  const discount = (c: Coupon) => totalPrice >= c.min_order ? Math.min(totalPrice, c.kind === 'flat' ? c.value : Math.round(totalPrice * c.value / 100)) : 0;
  const sorted = data ? [...data].sort((a, b) => discount(b) - discount(a)) : [];
  return <ScrollView testID="one-saver-screen" contentContainerStyle={styles.content}><View style={styles.hero}><View style={styles.heroTop}><OneGlyph size={35} /><Text testID="saver-heading" style={styles.heading}>One Saver</Text><Icon name="sparkles-outline" size={22} color={colors.lime} /></View><Text testID="saver-description" style={styles.copy}>A little smarter. A lot more saved.</Text><Text testID="saver-current-savings" style={styles.amount}>₹{Math.max(0, totalMrp - totalPrice)}<Text style={styles.amountMeta}> already saved on MRP</Text></Text><Text testID="saver-no-membership" style={styles.note}>Your cart’s savings hub. No membership fee.</Text></View><View style={styles.delivery}><Icon name="bicycle-outline" size={23} color={colors.forest} /><View style={styles.flex}><Text testID="saver-delivery-title" style={styles.title}>{totalPrice >= 199 ? 'Free delivery unlocked' : `₹${199 - totalPrice} to free delivery`}</Text><Text style={styles.detail}>Free delivery on baskets of ₹199 or more.</Text></View></View><Text testID="saver-coupons-heading" style={styles.section}>Your best offers</Text><Text testID="saver-coupon-policy" style={styles.detail}>One coupon per order. Sorted by what saves you most.</Text>{!data ? <LoadState error={isError} retry={refetch} /> : sorted.map((c, i) => { const eligible = totalItems > 0 && totalPrice >= c.min_order; return <View key={c.code} testID={`saver-offer-${c.code}`} style={styles.offer}><View style={styles.offerTop}><Icon name="pricetag-outline" size={20} color={colors.forest} /><Text style={styles.offerTitle}>{c.label}</Text>{i === 0 && eligible && <Text testID="saver-best-offer" style={styles.best}>BEST FOR YOU</Text>}</View><Text testID={`saver-description-${c.code}`} style={styles.detail}>{c.description}</Text><View style={styles.offerBottom}><View><Text testID={`saver-code-${c.code}`} style={styles.code}>{c.code}</Text><Text testID={`saver-value-${c.code}`} style={styles.detail}>{eligible ? `Save ₹${discount(c)}` : `Add ₹${Math.max(c.min_order - totalPrice, 0)}${totalItems ? ' more' : ' in items'} to use`}</Text></View><Pressable testID={`saver-apply-${c.code}`} disabled={!eligible || applying} onPress={() => onApply(c.code)} style={[styles.use, (!eligible || applying) && styles.disabled]}>{applying ? <ActivityIndicator color={colors.forest} /> : <Text style={styles.useText}>Apply</Text>}</Pressable></View></View>; })}</ScrollView>;
}
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 35 }, hero: { backgroundColor: colors.forestDeep, borderRadius: 28, padding: 22 }, heroTop: { flexDirection: 'row', alignItems: 'center', gap: 12 }, heading: { color: colors.surface, fontSize: 23, fontWeight: '700', flex: 1 }, copy: { color: colors.onSurfaceInverse, fontSize: 11, marginTop: 14 }, amount: { color: colors.lime, fontSize: 32, fontWeight: '700', marginTop: 25 }, amountMeta: { fontSize: 10, fontWeight: '400', color: colors.surface }, note: { color: colors.onSurfaceInverse, fontSize: 9, marginTop: 12 }, delivery: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 16, backgroundColor: colors.limeSoft, borderRadius: 23, marginTop: 16 }, flex: { flex: 1 }, title: { color: colors.forest, fontSize: 12, fontWeight: '700' }, detail: { color: colors.muted, fontSize: 10, lineHeight: 16, marginTop: 4 }, section: { color: colors.onSurface, fontSize: 18, fontWeight: '700', marginTop: 26 }, offer: { padding: 17, marginTop: 14, borderRadius: 24, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, offerTop: { flexDirection: 'row', alignItems: 'center', gap: 8 }, offerTitle: { color: colors.forest, fontSize: 16, fontWeight: '700', flex: 1 }, best: { color: colors.forest, fontSize: 7, backgroundColor: colors.limeSoft, padding: 6, borderRadius: 6 }, offerBottom: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 15 }, code: { color: colors.onSurface, fontSize: 12, fontWeight: '700', letterSpacing: 1 }, use: { minHeight: 44, minWidth: 80, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.lime, borderRadius: 24 }, useText: { color: colors.forestDeep, fontSize: 12, fontWeight: '700' }, disabled: { opacity: 0.35 } });