import { useEffect, useRef } from 'react';
import { View, Text, StyleSheet, Pressable, Animated } from 'react-native';
import { Image } from 'expo-image';
import Icon from '@react-native-vector-icons/ionicons';
import { usePathname, useRouter } from 'expo-router';
import { colors } from '../theme';
import { useCart } from '../cart';
import { useCustomer } from '../customer';
import { paletteFor } from '../departments';
import type { Product } from '../api';
import { nativeDriver, useMotionAllowed } from '../motion';
export function ProductCard({ product: p, width = 140, scope = '' }: { product: Product; width?: number | null; scope?: string }) {
  const router = useRouter(); const palette = paletteFor(usePathname()); const { add, remove, qtyOf } = useCart(); const { saved, toggleSaved, ready } = useCustomer();
  const qty = qtyOf(p.id); const id = scope ? `${scope}-${p.id}` : p.id; const isSaved = saved.includes(p.id); const narrow = !!width && width < 120;
  const bounce = useRef(new Animated.Value(1)).current; const motion = useMotionAllowed();
  useEffect(() => { if (!qty || !motion) return; const animation = Animated.sequence([Animated.timing(bounce, { toValue: 0.96, duration: 100, useNativeDriver: nativeDriver }), Animated.spring(bounce, { toValue: 1, friction: 3, useNativeDriver: nativeDriver })]); animation.start(); return () => animation.stop(); }, [qty, motion, bounce]);
  return <Animated.View testID={`product-card-${id}`} style={[s.card, width ? { width } : s.fill, { transform: [{ scale: bounce }] }]}>
    <View style={[s.imageWrap, narrow && s.smallImage]}><Pressable testID={`product-open-${id}`} accessibilityLabel={`View ${p.name}`} onPress={() => router.push(`/product/${p.id}` as any)} style={s.imagePress}><Image testID={`product-image-${id}`} source={p.image} style={s.image} contentFit="contain" transition={150} /></Pressable><Pressable testID={`save-product-${id}`} disabled={!ready} accessibilityLabel={`${isSaved ? 'Unsave' : 'Save'} ${p.name}`} accessibilityState={{ selected: isSaved }} onPress={() => { void toggleSaved(p.id).catch(() => {}); }} style={s.heart}><Icon name={isSaved ? 'heart' : 'heart-outline'} size={17} color={palette.color} /></Pressable>{!!p.discount_pct && <View style={s.discount}><Text testID={`product-discount-${id}`} style={[s.discountText, { color: palette.color }]}>{p.discount_pct}% OFF</Text></View>}</View>
    <Pressable testID={`product-name-open-${id}`} accessibilityLabel={`View ${p.name} details`} onPress={() => router.push(`/product/${p.id}` as any)} style={s.content}><Text testID={`product-name-${id}`} numberOfLines={2} style={s.name}>{p.name}</Text><Text testID={`product-weight-${id}`} numberOfLines={1} style={s.weight}>{p.weight}</Text></Pressable>
    <View style={[s.footer, narrow && s.narrowFooter]}><View style={s.priceWrap}><Text testID={`product-price-${id}`} style={s.price}>₹{p.price}</Text>{p.mrp > p.price && <Text testID={`product-mrp-${id}`} style={s.mrp}>₹{p.mrp}</Text>}</View>
    {!qty ? <Pressable testID={`add-btn-${id}`} accessibilityLabel={`Add ${p.name}`} onPress={e => add(p, { x: e.nativeEvent.pageX, y: e.nativeEvent.pageY })} style={({ pressed }) => [s.add, { backgroundColor: palette.fade }, pressed && s.pressed]}><Text style={[s.addText, { color: palette.color }]}>ADD</Text><Icon name="add" size={14} color={palette.color} /></Pressable> : <View testID={`stepper-${id}`} style={[s.stepper, { backgroundColor: palette.fade }]}><Pressable testID={`dec-${id}`} accessibilityLabel={`Remove one ${p.name}`} onPress={() => remove(p.id)} style={s.step}><Icon name="remove" size={15} color={palette.color} /></Pressable><Text testID={`qty-${id}`} style={[s.qty, { color: palette.color }]}>{qty}</Text><Pressable testID={`inc-${id}`} accessibilityLabel={`Add one ${p.name}`} onPress={e => add(p, { x: e.nativeEvent.pageX, y: e.nativeEvent.pageY })} style={s.step}><Icon name="add" size={15} color={palette.color} /></Pressable></View>}
    </View>
  </Animated.View>;
}
const s = StyleSheet.create({ card: { borderRadius: 17, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, overflow: 'hidden' }, fill: { width: '100%' }, imageWrap: { height: 112, backgroundColor: colors.cream }, smallImage: { height: 98 }, imagePress: { width: '100%', height: '100%' }, image: { width: '100%', height: '100%' }, heart: { position: 'absolute', top: 0, right: 0, width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, discount: { position: 'absolute', bottom: 5, left: 5, borderRadius: 5, padding: 4, backgroundColor: colors.glassBright, pointerEvents: 'none' }, discountText: { fontSize: 7, fontWeight: '800' }, content: { paddingHorizontal: 7, paddingTop: 9, minHeight: 55 }, name: { fontSize: 11, lineHeight: 15, fontWeight: '600', color: colors.onSurface, height: 30 }, weight: { fontSize: 9, color: colors.muted, marginTop: 4 }, footer: { paddingHorizontal: 6, paddingBottom: 5, paddingTop: 8, gap: 7 }, narrowFooter: { paddingHorizontal: 2 }, priceWrap: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 3 }, price: { fontSize: 14, fontWeight: '800', color: colors.onSurface }, mrp: { fontSize: 9, color: colors.muted, textDecorationLine: 'line-through' }, add: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, borderRadius: 12 }, addText: { fontSize: 10, fontWeight: '800' }, stepper: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderRadius: 12 }, step: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, qty: { fontSize: 10, fontWeight: '700', flexShrink: 1 }, pressed: { opacity: 0.65, transform: [{ scale: 0.97 }] } });