import { Modal, View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import Icon from '@react-native-vector-icons/ionicons';
import { colors } from '../theme';
export type CategoryOption = { id: string; label: string; selected: boolean; onPress: () => void };
export function SubcategoryOptions({ title, options, close, reset }: { title: string; options: CategoryOption[]; close: () => void; reset: () => void }) {
  const insets = useSafeAreaInsets();
  return <Modal transparent visible animationType="slide" onRequestClose={close}><View style={styles.overlay}><Pressable testID="category-options-backdrop" accessibilityLabel="Close filters" onPress={close} style={styles.backdrop} /><View testID="category-options-sheet" style={[styles.sheet, { paddingBottom: Math.max(24, insets.bottom) }]}><View style={styles.header}><Text testID="category-options-title" style={styles.title}>{title}</Text><Pressable testID="category-options-close" accessibilityLabel="Close filters" onPress={close} style={styles.round}><Icon name="close" size={22} color={colors.onSurface} /></Pressable></View><ScrollView testID="category-options-list" contentContainerStyle={styles.options}>{options.map(o => <Pressable testID={o.id} accessibilityRole="checkbox" accessibilityState={{ checked: o.selected }} key={o.id} onPress={o.onPress} style={styles.option}><Text style={styles.label}>{o.label}</Text><Icon name={o.selected ? 'checkmark-circle' : 'ellipse-outline'} size={23} color={o.selected ? colors.forest : colors.borderStrong} /></Pressable>)}</ScrollView><View style={styles.footer}><Pressable testID="category-options-reset" onPress={reset} style={styles.reset}><Text style={styles.buttonText}>Reset</Text></Pressable><Pressable testID="category-options-apply" onPress={close} style={styles.apply}><Text style={styles.buttonText}>Show items</Text></Pressable></View></View></View></Modal>;
}
const styles = StyleSheet.create({ overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: colors.overlay }, backdrop: { ...StyleSheet.absoluteFill, zIndex: 0 }, sheet: { maxHeight: '72%', backgroundColor: colors.surface, borderTopLeftRadius: 25, borderTopRightRadius: 25, padding: 20 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }, title: { fontSize: 21, fontWeight: '700', color: colors.onSurface }, round: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, options: { paddingBottom: 12 }, option: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.border, gap: 12 }, label: { flex: 1, color: colors.onSurface, fontSize: 14 }, footer: { flexDirection: 'row', gap: 10, marginTop: 12 }, reset: { minHeight: 48, paddingHorizontal: 24, borderWidth: 1, borderColor: colors.border, borderRadius: 14, justifyContent: 'center' }, apply: { flex: 1, minHeight: 48, backgroundColor: colors.lime, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, buttonText: { fontSize: 13, fontWeight: '700', color: colors.forest } });