import { useState } from 'react';
import { View, Text, TextInput, Pressable, StyleSheet } from 'react-native';
import Icon from '@react-native-vector-icons/ionicons';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Address, useCustomer } from '@/src/customer';
import { useDeliveryLocation } from '@/src/delivery-location';
import { AccountLayout, ActionButton, Message, accountStyles as s } from '@/src/components/account-layout';
import { colors } from '@/src/theme';
const empty: Address = { id: '', label: 'Home', name: '', phone: '', line: '', area: '', pin: '' };
export default function Addresses() {
  const { addresses, update, profile, ready } = useCustomer(); const delivery = useDeliveryLocation();
  const [draft, setDraft] = useState<Address | null>(null); const [removing, setRemoving] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const save = async () => {
    if (!draft) return; setError(''); setMessage('');
    if (draft.name.trim().length < 2 || draft.line.trim().length < 5 || draft.area.trim().length < 2) return setError('Add your name, a complete street address and area.');
    if (!/^[6-9]\d{9}$/.test(draft.phone)) return setError('Enter a valid 10-digit mobile number.');
    if (!/^[1-9]\d{5}$/.test(draft.pin)) return setError('Enter a valid 6-digit PIN code.');
    const next = { ...draft, id: draft.id || `address-${Date.now()}`, name: draft.name.trim(), line: draft.line.trim(), area: draft.area.trim() };
    setBusy(true); try { await update({ addresses: addresses.some(a => a.id === next.id) ? addresses.map(a => a.id === next.id ? next : a) : [...addresses, next] }); setDraft(null); setMessage('Address saved.'); } catch { setError('Could not save this address.'); } finally { setBusy(false); }
  };
  const remove = async (id: string) => { setBusy(true); try { await update({ addresses: addresses.filter(a => a.id !== id) }); setRemoving(''); setMessage('Address removed.'); } catch { setError('Could not remove this address.'); } finally { setBusy(false); } };
  const choose = async (a: Address) => { setBusy(true); try { const text = `${a.label}: ${a.line}, ${a.area}, ${a.pin}`; await AsyncStorage.setItem('one-latur-location', text); delivery.setLocation(text); setMessage(`Delivering to ${a.label}.`); } catch { setError('Could not select this address.'); } finally { setBusy(false); } };
  return <AccountLayout id="addresses" title="Your favourite places" subtitle="Save delivery details for home, work or someone special. Sample delivery service in Latur.">
    <Message id="address-error" text={error} error /><Message id="address-success" text={message} />
    {!addresses.length && !draft && <View testID="addresses-empty" style={s.card}><Icon name="location-outline" size={32} color={colors.shops} /><Text style={s.title}>A place for every delivery</Text><Text style={s.hint}>Add your first address to get started.</Text></View>}
    {addresses.map(a => <View testID={`address-card-${a.id}`} key={a.id} style={s.card}><View style={s.row}><Icon name={a.label === 'Work' ? 'briefcase-outline' : 'home-outline'} size={23} color={colors.shops} /><Text testID={`address-label-${a.id}`} style={s.title}>{a.label}</Text></View><Text testID={`address-details-${a.id}`} style={s.hint}>{a.name} · {a.phone}{'\n'}{a.line}, {a.area} · {a.pin}</Text><View style={s.row}><Pressable testID={`address-edit-${a.id}`} style={st.link} onPress={() => { setDraft(a); setError(''); setMessage(''); }}><Text style={st.linkText}>Edit</Text></Pressable><Pressable testID={`address-delete-${a.id}`} style={st.link} onPress={() => setRemoving(a.id)}><Text style={st.linkText}>Remove</Text></Pressable></View>{removing === a.id ? <View><Text testID="address-delete-confirmation" style={s.hint}>Remove this saved address?</Text><ActionButton id="address-confirm-delete" title="Yes, remove" onPress={() => remove(a.id)} busy={busy} /><Pressable testID="address-cancel-delete" style={st.link} onPress={() => setRemoving('')}><Text style={st.linkText}>Keep address</Text></Pressable></View> : <ActionButton id={`address-use-${a.id}`} title={delivery.location.includes(a.line) ? 'Selected for delivery' : 'Deliver here'} onPress={() => choose(a)} busy={busy} />}</View>)}
    {draft ? <View testID="address-form" style={s.card}><Text style={s.title}>{draft.id ? 'Edit address' : 'Add an address'}</Text><View style={s.row}>{['Home', 'Work', 'Other'].map(label => <Pressable key={label} testID={`address-type-${label.toLowerCase()}`} accessibilityState={{ selected: draft.label === label }} style={[st.chip, draft.label === label && st.selected]} onPress={() => setDraft({ ...draft, label })}><Text style={st.linkText}>{label}</Text></Pressable>)}</View>{[{ key: 'name', label: 'Receiver name' }, { key: 'phone', label: 'Mobile number' }, { key: 'line', label: 'Flat / building / street' }, { key: 'area', label: 'Area / city' }, { key: 'pin', label: 'PIN code' }].map(f => <View key={f.key}><Text style={s.label}>{f.label}</Text><TextInput testID={`address-${f.key}-input`} accessibilityLabel={f.label} style={s.input} value={draft[f.key as keyof Address]} editable={!busy} onChangeText={text => setDraft({ ...draft, [f.key]: text })} maxLength={f.key === 'phone' ? 10 : f.key === 'pin' ? 6 : 120} keyboardType={['phone', 'pin'].includes(f.key) ? 'number-pad' : 'default'} /></View>)}<ActionButton id="address-save" title="Save address" onPress={save} busy={busy} /><Pressable testID="address-cancel" style={st.link} onPress={() => setDraft(null)}><Text style={st.linkText}>Cancel</Text></Pressable></View> : <ActionButton id="address-add" title="Add a new address" disabled={!ready} onPress={() => { setDraft({ ...empty, name: profile.name, phone: profile.phone }); setError(''); setMessage(''); }} />}
  </AccountLayout>;
}
const st = StyleSheet.create({ link: { minHeight: 44, minWidth: 60, justifyContent: 'center' }, linkText: { color: colors.shops, fontWeight: '600', fontSize: 13 }, chip: { minHeight: 44, paddingHorizontal: 16, borderRadius: 22, justifyContent: 'center', backgroundColor: colors.shopsFade }, selected: { backgroundColor: colors.shopsTop } });