import { useState } from 'react';
import { View, Text, Pressable, TextInput, StyleSheet } from 'react-native';
import Icon from '@react-native-vector-icons/ionicons';
import { AccountLayout, ActionButton, Message, accountStyles as s } from '@/src/components/account-layout';
import { apiPost } from '@/src/api';
import { colors } from '@/src/theme';
const faq = [
  ['Where is my order?', 'Open Profile → My Orders to see your saved order and its illustrative delivery story. This sample app does not dispatch a real rider.'],
  ['Will I be charged at checkout?', 'No. Checkout creates a sample order. Payment-method selection saves your preference but does not collect money or bank details.'],
  ['How do I save my favourites?', 'Tap the heart on any product. Your favourites appear under Profile → Wishlist and remain saved on this device.'],
  ['How do referral rewards work?', 'You can copy or share your invite code. Referral tracking and rewards are not active yet, so sharing does not earn money.'],
];
export default function Help() {
  const [open, setOpen] = useState(-1); const [topic, setTopic] = useState('order'); const [message, setMessage] = useState(''); const [reference, setReference] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [receipt, setReceipt] = useState<string | null>(null);
  const send = async () => { setError(''); if (message.trim().length < 10) return setError('Please describe your question in at least 10 characters.'); setBusy(true); try { const result = await apiPost<{ id: string }>('/support-requests', { topic, message: message.trim(), reference: reference.trim() }); setReceipt(result.id); setMessage(''); } catch { setError('Could not save your request. Your message is still here; please try again.'); } finally { setBusy(false); } };
  return <AccountLayout id="help" title="A little help, right here" subtitle="Quick answers and a place to leave your questions."><View style={s.card}>{faq.map(([question, answer], i) => <View key={question}><Pressable testID={`help-faq-${i}`} accessibilityState={{ expanded: open === i }} style={st.faq} onPress={() => setOpen(open === i ? -1 : i)}><Text style={[s.label, s.flex]}>{question}</Text><Icon name={open === i ? 'remove' : 'add'} size={20} color={colors.shops} /></Pressable>{open === i && <Text testID={`help-answer-${i}`} style={s.hint}>{answer}</Text>}</View>)}</View><View style={s.card}><Text style={s.title}>Leave a support request</Text><Text testID="help-service-notice" style={s.hint}>Your request is saved in OneCity. Live chat, email delivery and response times are not connected yet. Do not include passwords, card details or sensitive information.</Text><View style={st.topics}>{['order', 'payment', 'profile', 'other'].map(t => <Pressable testID={`help-topic-${t}`} accessibilityState={{ selected: topic === t }} key={t} onPress={() => setTopic(t)} style={[st.topic, topic === t && st.selected]}><Text style={st.topicText}>{t}</Text></Pressable>)}</View><TextInput testID="help-reference" accessibilityLabel="Order reference, optional" placeholder="Order reference · optional" value={reference} onChangeText={setReference} maxLength={100} style={s.input} placeholderTextColor={colors.muted} /><TextInput testID="help-message" accessibilityLabel="Your question" placeholder="Tell us a little more…" value={message} onChangeText={setMessage} maxLength={2000} multiline textAlignVertical="top" style={[s.input, st.message]} placeholderTextColor={colors.muted} /><Message id="help-error" text={error} error /><ActionButton id="help-submit" title="Save support request" onPress={send} busy={busy} />{receipt && <View testID="help-receipt" style={st.receipt}><Icon name="checkmark-circle" size={24} color={colors.shops} /><Text selectable testID="help-reference-number" style={s.hint}>Request saved. Reference: {receipt}</Text></View>}</View></AccountLayout>;
}
const st = StyleSheet.create({ faq: { flexDirection: 'row', alignItems: 'center', gap: 8, minHeight: 48 }, topics: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, topic: { paddingHorizontal: 13, minHeight: 44, borderRadius: 22, justifyContent: 'center', backgroundColor: colors.shopsFade }, selected: { backgroundColor: colors.shopsTop }, topicText: { color: colors.shops, textTransform: 'capitalize', fontSize: 12 }, message: { minHeight: 120 }, receipt: { backgroundColor: colors.shopsFade, padding: 16, borderRadius: 16, gap: 10 } });