import { useEffect, useState } from 'react';
import { View, Text, ScrollView, Pressable, StyleSheet, ActivityIndicator } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { useRouter } from 'expo-router';
import AsyncStorage from '@react-native-async-storage/async-storage';
import Icon from '@react-native-vector-icons/ionicons';
import { colors } from '@/src/theme';
type Entry = { id: string; amount: number; label: string; date: string };
export default function Wallet() {
  const router = useRouter(); const [items, setItems] = useState<Entry[]>([]); const [ready, setReady] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { AsyncStorage.getItem('onecity-demo-wallet').then(raw => { setItems(raw ? JSON.parse(raw) : [{ id: 'welcome', amount: 250, label: 'Sample welcome credit', date: new Date().toISOString() }]); }).catch(() => setMessage('Could not load your demo wallet.')).finally(() => setReady(true)); }, []);
  const addDemo = async () => { if (busy || !ready) return; setBusy(true); const next = [{ id: Date.now().toString(), amount: 100, label: 'Sample top-up', date: new Date().toISOString() }, ...items]; try { await AsyncStorage.setItem('onecity-demo-wallet', JSON.stringify(next)); setItems(next); setMessage('₹100 demo credit added. No real money was used.'); } catch { setMessage('Could not save the demo credit. Please try again.'); } finally { setBusy(false); } };
  const balance = items.reduce((sum, t) => sum + t.amount, 0);
  return <ScrollView testID="wallet-screen" contentContainerStyle={styles.content}><View style={styles.header}><Pressable testID="wallet-back" accessibilityLabel="Go back" style={styles.round} onPress={() => router.canGoBack() ? router.back() : router.replace('/(tabs)' as any)}><Icon name="arrow-back" size={19} color={colors.onSurface} /></Pressable><Text style={styles.title}>Your little city wallet</Text></View><LinearGradient colors={[colors.forest, colors.walletInk]} style={styles.balanceCard}><View style={styles.balanceTop}><Icon name="wallet-outline" size={22} color={colors.lime} /><Text testID="wallet-demo-badge" style={styles.demoBadge}>DEMO WALLET</Text></View><Text style={styles.balanceLabel}>A little something for later</Text>{ready ? <Text testID="wallet-balance" style={styles.balance}>₹{balance.toLocaleString('en-IN')}<Text style={styles.decimals}>.00</Text></Text> : <ActivityIndicator color={colors.lime} />}<Text style={styles.balanceFoot}>OneCity · Sample balance only</Text><View style={styles.circle} /></LinearGradient>
    <View style={styles.actions}><Pressable testID="wallet-add-demo" disabled={!ready || busy} onPress={addDemo} style={styles.action}><Icon name="add-circle-outline" size={22} color={colors.forest} /><Text style={styles.actionText}>{busy ? 'Adding…' : 'Add ₹100 demo'}</Text></Pressable><Pressable testID="wallet-explore" onPress={() => router.navigate('/grocery' as any)} style={styles.action}><Icon name="basket-outline" size={22} color={colors.forest} /><Text style={styles.actionText}>Explore the city</Text></Pressable></View>
    {!!message && <Text testID="wallet-feedback" style={styles.message}>{message}</Text>}<Text testID="wallet-disclaimer" style={styles.notice}>This is a demo, not a real-money wallet. Credits cannot be paid in, withdrawn, transferred or used at checkout.</Text><Text style={styles.section}>A little activity</Text>{items.map(item => <View testID={`wallet-entry-${item.id}`} key={item.id} style={styles.entry}><View style={styles.entryIcon}><Icon name="arrow-down-outline" size={17} color={colors.forest} /></View><View style={styles.flex}><Text style={styles.entryTitle}>{item.label}</Text><Text style={styles.entryDate}>{new Date(item.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })} · Demo transaction</Text></View><Text style={styles.amount}>+₹{item.amount}</Text></View>)}</ScrollView>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 35 }, header: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 20 }, round: { width: 44, height: 44, borderRadius: 23, backgroundColor: colors.glassBright, alignItems: 'center', justifyContent: 'center' }, title: { fontSize: 20, letterSpacing: -0.6, fontWeight: '600', color: colors.onSurface }, balanceCard: { padding: 25, borderRadius: 32, minHeight: 220, overflow: 'hidden' }, balanceTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, demoBadge: { color: colors.limeSoft, fontSize: 8, letterSpacing: 1.2, backgroundColor: colors.whiteGlass, borderRadius: 14, padding: 8 }, balanceLabel: { color: colors.onSurfaceInverse, fontSize: 11, marginTop: 25 }, balance: { color: colors.surface, fontSize: 39, fontWeight: '500', marginTop: 8, letterSpacing: -1 }, decimals: { fontSize: 23, color: colors.cityMid }, balanceFoot: { color: colors.cityMid, fontSize: 9, marginTop: 22 }, circle: { position: 'absolute', width: 190, height: 190, borderRadius: 95, borderWidth: 25, borderColor: colors.whiteGlass, right: -90, bottom: -80 }, actions: { flexDirection: 'row', gap: 12, marginTop: 18 }, action: { flex: 1, minHeight: 85, borderRadius: 26, backgroundColor: colors.glassBright, alignItems: 'center', justifyContent: 'center', gap: 9 }, actionText: { color: colors.forest, fontSize: 10, fontWeight: '600' }, message: { fontSize: 11, color: colors.forest, marginTop: 15, lineHeight: 18 }, notice: { fontSize: 10, lineHeight: 17, color: colors.muted, marginVertical: 23 }, section: { color: colors.onSurface, fontSize: 18, fontWeight: '600', marginBottom: 15 }, entry: { flexDirection: 'row', alignItems: 'center', padding: 14, gap: 12, borderRadius: 22, backgroundColor: colors.glassBright, marginBottom: 10 }, entryIcon: { width: 38, height: 38, borderRadius: 20, backgroundColor: colors.limeSoft, alignItems: 'center', justifyContent: 'center' }, flex: { flex: 1 }, entryTitle: { fontSize: 11, fontWeight: '500', color: colors.onSurface }, entryDate: { fontSize: 9, color: colors.muted, marginTop: 5 }, amount: { fontSize: 13, fontWeight: '600', color: colors.forest } });