import { useState } from 'react';
import { View, Text, Pressable, StyleSheet, FlatList, ScrollView, useWindowDimensions } from 'react-native';
import { Image } from 'expo-image';
import { LinearGradient } from 'expo-linear-gradient';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import Icon from '@react-native-vector-icons/ionicons';
import { colors } from '@/src/theme';
import { useDiscovery } from '@/src/use-discovery';
import { LoadState } from '@/src/components/catalog-sections';
import { OneGlyph } from '@/src/components/one-button';

export default function Discover() {
  const { data, isError, refetch } = useDiscovery(); const [filter, setFilter] = useState('All');
  const insets = useSafeAreaInsets(); const { width } = useWindowDimensions(); const router = useRouter();
  const columns = width > 600 ? 4 : 3; const tileWidth = (width - 8 - (columns - 1) * 3) / columns;
  const filtered = data?.filter(r => filter === 'All' || (filter === 'Reels' ? !!r.video : filter === 'Food' ? r.product.department === 'food' : filter === 'Fresh' ? r.product.department === 'grocery' : ['beauty', 'pharmacy'].includes(r.product.department || '')));
  return <View testID="discover-screen" style={[styles.screen, { paddingTop: insets.top }]}>
    <View style={styles.header}><View><Text testID="discover-title" style={styles.title}>Discover<Text style={styles.green}>.</Text></Text><Text testID="discover-subtitle" style={styles.subtitle}>Your city, worth a closer look.</Text></View><Pressable testID="discover-ai-button" accessibilityLabel="Ask One AI" onPress={() => router.push('/assistant' as any)} style={styles.ai}><OneGlyph size={23} /><Text style={styles.aiLabel}>Ask AI</Text></Pressable></View>
    <ScrollView horizontal style={styles.filters} contentContainerStyle={styles.filterContent} showsHorizontalScrollIndicator={false}>{['All', 'Reels', 'Food', 'Fresh', 'Care'].map(f => <Pressable key={f} testID={`discover-filter-${f.toLowerCase()}`} accessibilityState={{ selected: filter === f }} onPress={() => setFilter(f)} style={[styles.chip, filter === f && styles.selected]}><Text style={[styles.chipText, filter === f && styles.selectedText]}>{f}</Text></Pressable>)}</ScrollView>
    {!data ? <LoadState error={isError} retry={refetch} /> : <FlatList testID="discover-grid" key={columns} numColumns={columns} data={filtered} keyExtractor={r => r.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.grid} columnWrapperStyle={styles.gridRow} ListHeaderComponent={<Text testID="discover-content-notice" style={styles.notice}>Curated sample reels & catalogue photo ads · tap to explore</Text>} ListEmptyComponent={<Text testID="discover-empty" style={styles.empty}>No discoveries in this filter yet. Try All.</Text>} renderItem={({ item: r, index }) => <Pressable testID={`discover-tile-${r.id}`} accessibilityLabel={`Open ${r.product.name} ${r.video ? 'reel' : 'photo ad'}`} onPress={() => router.push({ pathname: '/reels', params: { id: r.id } } as any)} style={({ pressed }) => [styles.tile, { width: tileWidth, height: tileWidth * 1.6 }, pressed && styles.pressed]}><Image testID={`discover-image-${r.id}`} source={r.product.image} contentFit="cover" style={StyleSheet.absoluteFill} transition={180} /><LinearGradient colors={[colors.transparent, colors.overlayDeep]} style={styles.gradient} /><View style={styles.topIcon}><Icon name={r.video ? 'play' : 'images-outline'} size={15} color={colors.surface} /></View>{index === 0 && filter === 'All' && <View style={styles.trending}><Text style={styles.trendingText}>FOR YOU</Text></View>}<View style={styles.caption}><Text testID={`discover-name-${r.id}`} style={styles.name} numberOfLines={2}>{r.product.name}</Text><Text testID={`discover-price-${r.id}`} style={styles.price}>₹{r.product.price}<Text style={styles.shop}> · Shop</Text></Text></View></Pressable>} />}
  </View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.surface }, header: { padding: 20, paddingTop: 18, paddingBottom: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { color: colors.onSurface, fontSize: 29, fontWeight: '800', letterSpacing: -1 }, green: { color: colors.forest }, subtitle: { fontSize: 11, color: colors.muted, marginTop: 4 }, ai: { backgroundColor: colors.brandPrimary, borderRadius: 22, minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 9, paddingHorizontal: 14 }, aiLabel: { color: colors.surface, fontSize: 11, fontWeight: '600' }, filters: { flexGrow: 0, maxHeight: 57 }, filterContent: { paddingHorizontal: 20, gap: 8, paddingBottom: 10 }, chip: { minHeight: 44, borderRadius: 24, paddingHorizontal: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.cream }, selected: { backgroundColor: colors.brandPrimary }, chipText: { color: colors.muted, fontSize: 11, fontWeight: '500' }, selectedText: { color: colors.lime }, grid: { paddingHorizontal: 4, paddingBottom: 135 }, gridRow: { gap: 3, marginBottom: 3 }, tile: { backgroundColor: colors.cream, overflow: 'hidden', borderRadius: 12 }, gradient: { position: 'absolute', left: 0, right: 0, bottom: 0, height: '60%' }, topIcon: { position: 'absolute', right: 7, top: 8, backgroundColor: colors.overlay, borderRadius: 10, padding: 4 }, caption: { position: 'absolute', left: 9, right: 6, bottom: 10 }, name: { color: colors.surface, fontWeight: '600', fontSize: 10, lineHeight: 14 }, price: { color: colors.lime, fontSize: 11, fontWeight: '700', marginTop: 5 }, shop: { color: colors.surface, fontSize: 8, fontWeight: '400' }, notice: { fontSize: 9, color: colors.muted, marginHorizontal: 12, marginTop: 3, marginBottom: 12 }, empty: { color: colors.muted, padding: 30, fontSize: 13 }, trending: { position: 'absolute', left: 6, top: 9, padding: 4, borderRadius: 6, backgroundColor: colors.lime }, trendingText: { fontSize: 6, fontWeight: '800', color: colors.forestDeep }, pressed: { opacity: 0.7, transform: [{ scale: 0.97 }] } });