import { View, Text, ScrollView, Pressable, StyleSheet, useWindowDimensions } from 'react-native';
import { Image } from 'expo-image';
import { useLocalSearchParams, useRouter } from 'expo-router';
import Icon from '@react-native-vector-icons/ionicons';
import { LinearGradient } from 'expo-linear-gradient';
import { colors } from '@/src/theme';
import { useCatalog } from '@/src/use-catalog';
import { ProductCard } from '@/src/components/product-card';
import { LoadState } from '@/src/components/catalog-sections';
import { useFollowedStores } from '@/src/followed';
export default function BrandCollection() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { data, isError, refetch } = useCatalog(); const router = useRouter(); const width = useWindowDimensions().width; const { isFollowing, toggle } = useFollowedStores();
  if (!data) return <LoadState error={isError} retry={refetch} />;
  const brand = data.brands.find(b => b.id === id); const products = data.products.filter(p => p.brand_id === id || (!p.brand_id && p.store_id === id));
  if (!brand) return <View style={styles.empty}><Text style={styles.title}>Brand not found</Text><Pressable testID="brand-not-found-home" style={styles.link} onPress={() => router.replace('/(tabs)' as any)}><Text style={styles.linkText}>Back to OneCity</Text></Pressable></View>;
  const followed = isFollowing(id); const cols = width > 600 ? 3 : 2;
  return <ScrollView testID={`brand-screen-${id}`} contentContainerStyle={styles.content}><View style={styles.backRow}><Pressable testID="brand-back" accessibilityLabel="Go back" onPress={() => router.canGoBack() ? router.back() : router.replace('/(tabs)' as any)} style={styles.round}><Icon name="arrow-back" size={18} color={colors.onSurface} /></Pressable><Text style={styles.eyebrow}>THE BRAND EDIT</Text><Pressable testID={`brand-store-${id}`} style={styles.link} onPress={() => router.push(`/store/${id}` as any)}><Text style={styles.linkText}>Store profile</Text></Pressable></View>
    <LinearGradient colors={[colors.glassBright, colors.glass]} style={styles.hero}><View style={styles.logoWrap}>{brand.logo ? <Image testID={`brand-logo-${id}`} source={brand.logo} style={styles.logo} contentFit="contain" /> : <Text style={styles.logoText}>{brand.name}</Text>}</View><Text testID="brand-collection-title" style={styles.title}>{brand.name}</Text><Text style={styles.tagline}>{brand.tagline}</Text><Pressable testID={`brand-follow-${id}`} onPress={() => toggle(id)} style={[styles.follow, followed && styles.following]}><Icon name={followed ? 'heart' : 'heart-outline'} size={15} color={colors.forest} /><Text style={styles.linkText}>{followed ? 'Following' : 'Follow brand'}</Text></Pressable></LinearGradient>
    <View style={styles.sheet}><View style={styles.heading}><Text testID="brand-product-count" style={styles.collectionTitle}>More from {brand.name}</Text><Text style={styles.count}>{products.length} little finds</Text></View><View style={styles.grid}>{products.map(p => <ProductCard key={p.id} product={p} width={(width-40-(cols-1)*12)/cols} scope={`brand-${id}`} />)}</View><Text testID="brand-sample-notice" style={styles.notice}>Sample brand collection. Listings, product imagery and prices are for exploring the app, not an official brand partnership.</Text></View>
  </ScrollView>;
}
const styles = StyleSheet.create({ content: { paddingBottom: 30 }, backRow: { flexDirection: 'row', paddingHorizontal: 20, alignItems: 'center', justifyContent: 'space-between' }, round: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.glassBright, alignItems: 'center', justifyContent: 'center' }, eyebrow: { fontSize: 8, letterSpacing: 1.2, color: colors.muted }, link: { minHeight: 44, justifyContent: 'center' }, linkText: { color: colors.forest, fontSize: 10, fontWeight: '600' }, hero: { margin: 20, marginTop: 12, borderRadius: 35, padding: 25, alignItems: 'center' }, logoWrap: { height: 75, width: 110, borderRadius: 28, backgroundColor: colors.glassBright, alignItems: 'center', justifyContent: 'center', marginBottom: 15 }, logo: { width: 83, height: 53 }, logoText: { fontSize: 20, fontWeight: '700', color: colors.onSurface }, title: { fontSize: 25, fontWeight: '600', color: colors.onSurface }, tagline: { fontSize: 11, color: colors.muted, marginTop: 9, textAlign: 'center' }, follow: { flexDirection: 'row', alignItems: 'center', gap: 7, minHeight: 44, paddingHorizontal: 20, borderRadius: 24, backgroundColor: colors.glassBright, marginTop: 17 }, following: { backgroundColor: colors.limeSoft }, sheet: { borderTopLeftRadius: 34, borderTopRightRadius: 34, backgroundColor: colors.glassBright }, heading: { padding: 20, paddingTop: 25 }, collectionTitle: { fontSize: 18, fontWeight: '600', color: colors.onSurface }, count: { fontSize: 10, color: colors.muted, marginTop: 5 }, grid: { flexDirection: 'row', flexWrap: 'wrap', paddingHorizontal: 20, gap: 12 }, notice: { color: colors.muted, fontSize: 9, lineHeight: 15, margin: 24 }, empty: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 20 } });